### ISSUE TITLE
Play Vimeo video by manually typing its ID in the addon interface

### ISSUE THREAD

**Issue by michael112** [jaylinski/kodi-addon-vimeo#58] opened 2021-05-22 10:29 UTC
Hey,
I would like to add the possiblity to manually type Vimeo video ID so I could play the video like in the browser on the URL: https://player.vimeo.com/video/<VIDEO_ID>.
Perhaps it is possible by this: plugin://plugin.video.vimeo/play/?video_id=1 but it's not possible using the addon user interface (as far as I'm concerned).
I cannot do this by typing the ID in "Search" field, because it doesn't return any results.

**Comment by jaylinski** [comment] 2021-05-22 20:01
@michael112 If I want to share a specific Vimeo video, I always use Kore (https://github.com/xbmc/Kore) if I'm on my Android phone, or Kodi Echo (https://github.com/jaylinski/kodi-echo), if I'm in my Firefox browser.

Would this be an option for you?

If not, were would you put this option? Maybe in the "Search"-folder? :thinking:

**Comment by thelabcat** [comment] 2021-08-16 16:54
I second the motion, sort of. I'm looking for an addon to play player.vimeo.com URLs I know how to retrieve. I'm just unfamiliar with the Kodi API at the moment...

**Comment by thelabcat** [comment] 2021-08-16 17:26
Maybe if you made a partial add-on with the code to play the URLs and list them, but then left kind of a blank section for how to retrieve them and return as a list or other hierarchical set.￼ that would be really extra nice :-)￼

**Comment by jaylinski** [comment] 2021-08-17 09:42
@thelabcat This already works. You can extract the video ID from your `player.vimeo.com`-URL and call the plugin via `plugin://plugin.video.vimeo/play/?video_id=<videoID>`.

Example: https://player.vimeo.com/video/154373242
API endpoint: plugin://plugin.video.vimeo/play/?video_id=154373242

**Comment by thelabcat** [comment] 2021-08-17 14:02
Thank you for replying. I've been looking at the API, and I have somewhat gathered that, with the right configuration, I could do that. I'm glad you confirmed it :-) The problem now is… I am REALLY unfamiliar with the Kodi API.￼￼ I have tried creating a simple test add-on and copying the libraries over from yours, but it didn't work: It got stuck at trying to import requests.￼

I would actually like to commission you to do this add-on for me in full, but I do not know how to communicate in private on GitHub. Do you know how to enter a private discussion?￼

**Comment by jaylinski** [comment] 2021-08-17 16:29
@thelabcat I added an email-address to my profile page so you can write me in private.

**Comment by thelabcat** [comment] 2021-08-17 19:19
Thanks!

*they would not consider

**Comment by thelabcat** [comment] 2021-08-18 14:16
Emails sent, although I have stayed away from Vimeo-related stuff as the site I am wanting also hosts a listed channel on another video site that provides true APIs.

**Comment by jaylinski** [comment] 2021-11-27 16:27
Closing this because an alternative solution was found.

**Closed by jaylinski** 2021-11-27 16:27 UTC
Labels: enhancement
